# Array Manipulation


### Array Manipulation - Changing shape


In [72]:
import numpy as np

a = np.arange(9)
print("The original array:")
print(a)
print()

b = a.reshape(3, 3)
print()
print("Modified Array: ")
print(b)

The original array:
[0 1 2 3 4 5 6 7 8]


Modified Array: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [73]:
print(b.flatten())

[0 1 2 3 4 5 6 7 8]


In [74]:
b.flatten(order="F")

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [75]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
print(np.transpose(a))

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [77]:
b = np.arange(8).reshape(2, 4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
c = b.reshape(2, 2, 2)
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [79]:
np.rollaxis(c, 2, 1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [80]:
np.swapaxes(c, 2, 1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

## Numpy Arithematic Operations


In [81]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
b = np.array([10, 10, 10])
b

array([10, 10, 10])

In [83]:
np.add(a, b)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [84]:
np.subtract(a, b)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [85]:
np.multiply(a, b)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [86]:
np.divide(a, b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

## Slicing


In [87]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [88]:
a[:4]

array([0, 1, 2, 3])

In [89]:
a[5]

5

In [91]:
s = slice(2,12,2)
a[s]

array([ 2,  4,  6,  8, 10])

## Iterating Over Array

In [97]:
a = np.arange(0,45,5)
a = a.reshape(3,3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [98]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40


### Iteration order (c-style and f-style)

In [100]:
print(a)
for  x in np.nditer(a, order = "C"):
    print(x)

for x in np.nditer(a, order = "f"):
    print(x)    

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40
0
15
30
5
20
35
10
25
40
